// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FeedService is exposed to the frontend via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../internal/api/models.js";

/**
 * AddFeed fetches and parses feedURL, then persists the feed and its items.
 * @param {string} feedURL
 * @returns {$CancellablePromise<api$0.Feed>}
 */
export function AddFeed(feedURL) {
    return $Call.ByID(1716605960, feedURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AddFeedFromSearch is AddFeed but uses artworkURL directly as the icon
 * instead of the favicon-discovery site scan, which often finds nothing
 * for a podcast's own site.
 * @param {string} feedURL
 * @param {string} artworkURL
 * @returns {$CancellablePromise<api$0.Feed>}
 */
export function AddFeedFromSearch(feedURL, artworkURL) {
    return $Call.ByID(2532603396, feedURL, artworkURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} feedID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFeed(feedID) {
    return $Call.ByID(3635964346, feedID);
}

/**
 * DiscoverFeeds scans siteURL's HTML for feed links, for when AddFeed
 * fails because siteURL is a webpage rather than a feed directly.
 * @param {string} siteURL
 * @returns {$CancellablePromise<api$0.DiscoveredFeed[]>}
 */
export function DiscoverFeeds(siteURL) {
    return $Call.ByID(638028247, siteURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ItemCount reports how many items are stored for feedID, so the UI can
 * show a count without fetching every item's full fields.
 * @param {number} feedID
 * @returns {$CancellablePromise<number>}
 */
export function ItemCount(feedID) {
    return $Call.ByID(3749001981, feedID);
}

/**
 * @param {number} itemID
 * @returns {$CancellablePromise<string>}
 */
export function ItemMarkdown(itemID) {
    return $Call.ByID(617211291, itemID);
}

/**
 * @returns {$CancellablePromise<api$0.Feed[]>}
 */
export function ListFeeds() {
    return $Call.ByID(1402974494).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListItems returns feedID's items, newest first.
 * @param {number} feedID
 * @returns {$CancellablePromise<api$0.Item[]>}
 */
export function ListItems(feedID) {
    return $Call.ByID(4029245267, feedID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * RefreshAllFeeds queues an independent refresh per feed, so one slow or
 * failing feed doesn't block or fail the others.
 * @returns {$CancellablePromise<void>}
 */
export function RefreshAllFeeds() {
    return $Call.ByID(3899018096);
}

/**
 * RefreshFeed queues a background refetch and returns immediately; the
 * result arrives later via the "feed-refreshed" event.
 * 
 * ponytail: one refresh in flight per feed isn't enforced — a double-click
 * can queue two overlapping fetches. Upsert idempotency makes it harmless
 * today, just wasteful; add de-duplication if that changes.
 * @param {number} feedID
 * @returns {$CancellablePromise<void>}
 */
export function RefreshFeed(feedID) {
    return $Call.ByID(3427913176, feedID);
}

/**
 * SearchPodcasts queries iTunes for podcasts matching term.
 * @param {string} term
 * @returns {$CancellablePromise<api$0.PodcastResult[]>}
 */
export function SearchPodcasts(term) {
    return $Call.ByID(529381604, term).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

// Private type creation functions
const $$createType0 = api$0.Feed.createFrom;
const $$createType1 = api$0.DiscoveredFeed.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
const $$createType4 = api$0.Item.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = api$0.PodcastResult.createFrom;
const $$createType7 = $Create.Array($$createType6);
