// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FeedService is exposed to the frontend via Wails bindings. Every method
 * takes a leading context.Context, which Wails supplies from the request
 * lifecycle without exposing it to the JS caller.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../internal/api/models.js";

/**
 * AddFeed fetches and parses feedURL, then persists the feed and its items.
 * @param {string} feedURL
 * @returns {$CancellablePromise<api$0.Feed>}
 */
export function AddFeed(feedURL) {
    return $Call.ByID(1716605960, feedURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AddFeedFromSearch adds feedURL the same way AddFeed does, but uses
 * artworkURL directly as the icon instead of the favicon-discovery site
 * scan — iTunes already supplies reliable artwork for its own search
 * results, which a podcast's own site frequently lacks a usable favicon
 * for (confirmed in practice: InnerFrench has iTunes artwork but no
 * discoverable site icon at all).
 * @param {string} feedURL
 * @param {string} artworkURL
 * @returns {$CancellablePromise<api$0.Feed>}
 */
export function AddFeedFromSearch(feedURL, artworkURL) {
    return $Call.ByID(2532603396, feedURL, artworkURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} feedID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFeed(feedID) {
    return $Call.ByID(3635964346, feedID);
}

/**
 * DiscoverFeeds scans siteURL's HTML for feed links, for when AddFeed
 * fails because siteURL is a webpage rather than a feed directly. Returns
 * every feed the page advertises (a site can have more than one, e.g.
 * separate blog/photo feeds) so the caller can offer a choice instead of
 * one being picked automatically.
 * @param {string} siteURL
 * @returns {$CancellablePromise<api$0.DiscoveredFeed[]>}
 */
export function DiscoverFeeds(siteURL) {
    return $Call.ByID(638028247, siteURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ItemCount reports how many items are stored for feedID, so the UI can
 * show a count without fetching every item's full fields.
 * @param {number} feedID
 * @returns {$CancellablePromise<number>}
 */
export function ItemCount(feedID) {
    return $Call.ByID(3749001981, feedID);
}

/**
 * @returns {$CancellablePromise<api$0.Feed[]>}
 */
export function ListFeeds() {
    return $Call.ByID(1402974494).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListItems returns feedID's items, newest first.
 * @param {number} feedID
 * @returns {$CancellablePromise<api$0.Item[]>}
 */
export function ListItems(feedID) {
    return $Call.ByID(4029245267, feedID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * RefreshAllFeeds queues an independent background refresh for every
 * subscribed feed and returns as soon as they're all queued. Each feed
 * refreshes on its own — reusing the exact same independent function
 * RefreshFeed uses per feed — so one slow or failing feed doesn't block or
 * fail the others; each reports its own "feed-refreshed" event as it
 * completes.
 * @returns {$CancellablePromise<void>}
 */
export function RefreshAllFeeds() {
    return $Call.ByID(3899018096);
}

/**
 * RefreshFeed queues a background refetch of feedID and returns as soon as
 * it's queued — it does not wait for the network fetch to finish. The
 * result (updated feed, or an error) is reported via the "feed-refreshed"
 * event, so a slow or failing refresh never blocks the caller.
 * 
 * ponytail: one refresh in flight per feed isn't enforced — a double-click
 * can queue two overlapping fetches. Add de-duplication if that turns out
 * to matter in practice; upsert idempotency means it's harmless today, just
 * wasteful.
 * @param {number} feedID
 * @returns {$CancellablePromise<void>}
 */
export function RefreshFeed(feedID) {
    return $Call.ByID(3427913176, feedID);
}

/**
 * SearchPodcasts queries iTunes for podcasts matching term, for the
 * discover-feeds UI.
 * @param {string} term
 * @returns {$CancellablePromise<api$0.PodcastResult[]>}
 */
export function SearchPodcasts(term) {
    return $Call.ByID(529381604, term).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

// Private type creation functions
const $$createType0 = api$0.Feed.createFrom;
const $$createType1 = api$0.DiscoveredFeed.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
const $$createType4 = api$0.Item.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = api$0.PodcastResult.createFrom;
const $$createType7 = $Create.Array($$createType6);
