// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../internal/api/models.js";

/**
 * @param {string} feedURL
 * @returns {$CancellablePromise<api$0.Feed>}
 */
export function AddFeed(feedURL) {
    return $Call.ByID(1716605960, feedURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} feedURL
 * @param {string} artworkURL
 * @returns {$CancellablePromise<api$0.Feed>}
 */
export function AddFeedFromSearch(feedURL, artworkURL) {
    return $Call.ByID(2532603396, feedURL, artworkURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} itemID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDownload(itemID) {
    return $Call.ByID(1863193026, itemID);
}

/**
 * @param {number} feedID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFeed(feedID) {
    return $Call.ByID(3635964346, feedID);
}

/**
 * @param {string} siteURL
 * @returns {$CancellablePromise<api$0.DiscoveredFeed[]>}
 */
export function DiscoverFeeds(siteURL) {
    return $Call.ByID(638028247, siteURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} itemID
 * @returns {$CancellablePromise<void>}
 */
export function DownloadEpisode(itemID) {
    return $Call.ByID(223036006, itemID);
}

/**
 * @param {number} feedID
 * @returns {$CancellablePromise<api$0.Feed>}
 */
export function GetFeed(feedID) {
    return $Call.ByID(710938923, feedID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<api$0.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(3614473298).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {number} feedID
 * @returns {$CancellablePromise<number>}
 */
export function ItemCount(feedID) {
    return $Call.ByID(3749001981, feedID);
}

/**
 * @param {number} itemID
 * @returns {$CancellablePromise<string>}
 */
export function ItemMarkdown(itemID) {
    return $Call.ByID(617211291, itemID);
}

/**
 * @returns {$CancellablePromise<api$0.Feed[]>}
 */
export function ListFeeds() {
    return $Call.ByID(1402974494).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {number} feedID
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<api$0.Item[]>}
 */
export function ListItems(feedID, limit, offset) {
    return $Call.ByID(4029245267, feedID, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RefreshAllFeeds() {
    return $Call.ByID(3899018096);
}

/**
 * @param {number} feedID
 * @returns {$CancellablePromise<void>}
 */
export function RefreshFeed(feedID) {
    return $Call.ByID(3427913176, feedID);
}

/**
 * @param {api$0.Settings} settings
 * @returns {$CancellablePromise<api$0.Settings>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(3573394701, settings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} term
 * @returns {$CancellablePromise<api$0.PodcastResult[]>}
 */
export function SearchPodcasts(term) {
    return $Call.ByID(529381604, term).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {number} feedID
 * @param {string} title
 * @param {string} url
 * @returns {$CancellablePromise<api$0.Feed>}
 */
export function UpdateFeed(feedID, title, url) {
    return $Call.ByID(3440431000, feedID, title, url).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = api$0.Feed.createFrom;
const $$createType1 = api$0.DiscoveredFeed.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = api$0.Settings.createFrom;
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = api$0.Item.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = api$0.PodcastResult.createFrom;
const $$createType8 = $Create.Array($$createType7);
