// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../internal/api/models.js";

export class EpisodeDownloadEvent {
    /**
     * Creates a new EpisodeDownloadEvent instance.
     * @param {Partial<EpisodeDownloadEvent>} [$$source = {}] - The source object to create the EpisodeDownloadEvent.
     */
    constructor($$source = {}) {
        if (!("itemId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["itemId"] = 0;
        }
        if (!("downloaded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloaded"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["done"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["downloadFilename"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EpisodeDownloadEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EpisodeDownloadEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EpisodeDownloadEvent(/** @type {Partial<EpisodeDownloadEvent>} */($$parsedSource));
    }
}

/**
 * FeedRefreshResult is the payload of the "feed-refreshed" event.
 */
export class FeedRefreshResult {
    /**
     * Creates a new FeedRefreshResult instance.
     * @param {Partial<FeedRefreshResult>} [$$source = {}] - The source object to create the FeedRefreshResult.
     */
    constructor($$source = {}) {
        if (!("feedId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedId"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {api$0.Feed | undefined}
             */
            this["feed"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeedRefreshResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FeedRefreshResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("feed" in $$parsedSource) {
            $$parsedSource["feed"] = $$createField1_0($$parsedSource["feed"]);
        }
        return new FeedRefreshResult(/** @type {Partial<FeedRefreshResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = api$0.Feed.createFrom;
