// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DiscoveredFeed is one feed link found on a page by
 * internal/feed.DiscoverFeedURLs.
 */
export class DiscoveredFeed {
    /**
     * Creates a new DiscoveredFeed instance.
     * @param {Partial<DiscoveredFeed>} [$$source = {}] - The source object to create the DiscoveredFeed.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoveredFeed instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiscoveredFeed}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscoveredFeed(/** @type {Partial<DiscoveredFeed>} */($$parsedSource));
    }
}

/**
 * Feed is a subscribed feed as stored in internal/db.
 */
export class Feed {
    /**
     * Creates a new Feed instance.
     * @param {Partial<Feed>} [$$source = {}] - The source object to create the Feed.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {FeedKind}
             */
            this["kind"] = FeedKind.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * Icon is the raw downloaded icon image (site favicon today; may be
             * reused for podcast artwork etc. later), or nil if none was found.
             * encoding/json marshals a []byte as a base64 string automatically, so
             * the frontend can use it directly in a data: URI.
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["iconMime"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Feed instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Feed}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("icon" in $$parsedSource) {
            $$parsedSource["icon"] = $$createField4_0($$parsedSource["icon"]);
        }
        return new Feed(/** @type {Partial<Feed>} */($$parsedSource));
    }
}

/**
 * FeedKind is inferred from the feed's own content (any item with an
 * audio enclosure means Podcast), never trusted from caller input.
 * @readonly
 * @enum {number}
 */
export const FeedKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    FeedKindPodcast: 0,
    FeedKindArticle: 1,
};

/**
 * Item is a single feed entry. ID and FeedID are zero until the item has
 * been persisted via internal/db.
 */
export class Item {
    /**
     * Creates a new Item instance.
     * @param {Partial<Item>} [$$source = {}] - The source object to create the Item.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("feedId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["link"] = "";
        }
        if (!("pubDate" in $$source)) {
            /**
             * RFC3339, best-effort from the feed
             * @member
             * @type {string}
             */
            this["pubDate"] = "";
        }
        if (!("audioUrl" in $$source)) {
            /**
             * empty => article, not a podcast episode
             * @member
             * @type {string}
             */
            this["audioUrl"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * short teaser, always feed-supplied
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("contentEncoded" in $$source)) {
            /**
             * full body if the feed included one; empty otherwise
             * @member
             * @type {string}
             */
            this["contentEncoded"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Item instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Item}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Item(/** @type {Partial<Item>} */($$parsedSource));
    }
}

/**
 * PodcastResult is one match from an iTunes podcast search.
 */
export class PodcastResult {
    /**
     * Creates a new PodcastResult instance.
     * @param {Partial<PodcastResult>} [$$source = {}] - The source object to create the PodcastResult.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("feedUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["feedUrl"] = "";
        }
        if (!("artworkUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artworkUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PodcastResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PodcastResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PodcastResult(/** @type {Partial<PodcastResult>} */($$parsedSource));
    }
}
