// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DiscoveredFeed {
    /**
     * Creates a new DiscoveredFeed instance.
     * @param {Partial<DiscoveredFeed>} [$$source = {}] - The source object to create the DiscoveredFeed.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoveredFeed instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiscoveredFeed}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscoveredFeed(/** @type {Partial<DiscoveredFeed>} */($$parsedSource));
    }
}

export class Feed {
    /**
     * Creates a new Feed instance.
     * @param {Partial<Feed>} [$$source = {}] - The source object to create the Feed.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {FeedKind}
             */
            this["kind"] = FeedKind.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * []byte auto-marshals to base64
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["iconMime"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Feed instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Feed}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("icon" in $$parsedSource) {
            $$parsedSource["icon"] = $$createField4_0($$parsedSource["icon"]);
        }
        return new Feed(/** @type {Partial<Feed>} */($$parsedSource));
    }
}

/**
 * FeedKind is inferred from content, not trusted from caller input.
 * @readonly
 * @enum {number}
 */
export const FeedKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    FeedKindPodcast: 0,
    FeedKindArticle: 1,
};

export class Item {
    /**
     * Creates a new Item instance.
     * @param {Partial<Item>} [$$source = {}] - The source object to create the Item.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("feedId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedId"] = 0;
        }
        if (!("guid" in $$source)) {
            /**
             * stable identity; Link is often absent or shared
             * @member
             * @type {string}
             */
            this["guid"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["link"] = "";
        }
        if (!("pubDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pubDate"] = "";
        }
        if (!("audioUrl" in $$source)) {
            /**
             * empty => article
             * @member
             * @type {string}
             */
            this["audioUrl"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("contentEncoded" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentEncoded"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["downloadFilename"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["transcriptUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["transcriptType"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Item instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Item}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Item(/** @type {Partial<Item>} */($$parsedSource));
    }
}

export class PodcastResult {
    /**
     * Creates a new PodcastResult instance.
     * @param {Partial<PodcastResult>} [$$source = {}] - The source object to create the PodcastResult.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("feedUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["feedUrl"] = "";
        }
        if (!("artworkUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artworkUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PodcastResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PodcastResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PodcastResult(/** @type {Partial<PodcastResult>} */($$parsedSource));
    }
}

export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * "dark" or "light"
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("playbackSpeed" in $$source)) {
            /**
             * 0.5–3
             * @member
             * @type {number}
             */
            this["playbackSpeed"] = 0;
        }
        if (!("whisperModel" in $$source)) {
            /**
             * tiny, base, small, medium, large
             * @member
             * @type {string}
             */
            this["whisperModel"] = "";
        }
        if (!("cloudTranscription" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cloudTranscription"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}
